### ISSUE TITLE
Limit the usage of resources of a package

### ISSUE THREAD

**Issue by tropicar** [dappnode/DAppNode#419]
Because of the problem of one of the main package of dappnode, nethermind-xdai where the usage of resources is a problem for the host machine, we will implement this feature of docker where we can define how many resources will be used by a package.

The steps to implement this feature are the next ones:

- [x] - DAppNodeSDK code,dappnodesdk has to recognize these values from the docker-compose

- [x]  DAppManager code, dappamanager has to understand these new values and create containers with this configurations

- [ ]  Create integration tests with this new feature

- [ ]  Test this new feature in some package

References about this docker-compose feature:
- https://docs.docker.com/config/containers/resource_constraints/
- https://linuxhint.com/docker_compose_memory_limits/#:~:text=The%20MEM%20USAGE%2FLIMIT%20is,start%20writing%20docker%2Dcompose%20scripts
- https://www.baeldung.com/ops/docker-memory-limit

**Comment by tropicar** [comment]
The code of dappnodesdk and dappmanager is created but it seems there are some problems:
Testing the changes, the docker-compose gets the deploy values and it seems these values are not recognized by docker. Researching about this issue.
If we execute the command docker-info in the dappnode machine, we see this message:
`WARNING: No swap limit support`
Following this thread https://phoenixnap.com/kb/docker-memory-and-cpu-limit we have to set up some changes in the os. we have to test everything with these changes and check if the limits work.

**Comment by tropicar** [comment]
When the DAppNode installes a packages with these limitation options, in the docker-compose that you can find in the dappmanager this options are added but they are not applied.
```
deploy:
  resource:
    limits: 
      memory: 200M
```
This option is compatible with docker-compose version 3.5 and locally, if you run a docker-compose with docker-compose build and docker-compose run, the limit is set up. But in the DAppNode does not happen.

**Comment by tropicar** [comment]
Installing a package with the same options in the docker-compose and Dockerfile:
the output of:
```
docker stats
```
Is the next one:
```
1.316MiB / 58.98GiB
```
There are no limits for the container.

**Comment by tropicar** [comment]
The docker-compose file that is on the dappmanager is well parsed?
The answer is yes, if we check the docker-compose of the package we are testing with this limitation optionsin the dappmanager `/usr/src/dappnode/dnp_repo`
The docker-compose is:
```
version: '3.5'
services:
  test:
    container_name: DAppNodePackage-test.test-limit.public.dappnode.eth
    deploy:
      resources:
        limits:
          memory: 5000M
    dns: 172.33.1.2
    image: 'test.test-limit.public.dappnode.eth:0.1.0'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    networks:
      dncore_network:
        aliases:
          - test.test-limit.public.dappnode
    restart: unless-stopped
    labels:
      dappnode.dnp.dnpName: test-limit.public.dappnode.eth
      dappnode.dnp.version: 0.1.0
      dappnode.dnp.serviceName: test
      dappnode.dnp.dependencies: '{}'
      dappnode.dnp.avatar: /ipfs/QmT4nqgeAbKtRye1p8eKm9EGWQQZyW3JBQnk2nEiERWvJm
      dappnode.dnp.origin: /ipfs/QmaGBF584FxFz2BhCxNyMZMKXoJzdEnyvuiSJDEPCrKq3P
      dappnode.dnp.isCore: 'false'
      dappnode.dnp.isMain: 'true'
networks:
  dncore_network:
    external: true
```

**Comment by tropicar** [comment]
The next thing is, how the dappmanager run the container, there are mainly 2 functions implied:
```export function dockerComposeUp(
  dcPath: string,
  options: DockerComposeUpOptions = {}
): Promise<string> {
  // --detach is invalid with --no-start
  if (options.noStart) options.detach = false;
  return execDockerCompose(
    dcPath,
    "up",
    {
      noStart: options.noStart,
      detach: options.detach ?? true,
      forceRecreate: options.forceRecreate,
      timeout: options.timeout,
      removeOrphans: options.removeOrphans
    },
    options.serviceNames
  );
}
```
And
```
async function execDockerCompose(
  dcPath: string,
  subcommand: string,
  kwargs?: Kwargs,
  serviceNames?: string[]
): Promise<string> {
  // Usage: subcommand [options] [--scale SERVICE=NUM...] [SERVICE...]
  return shell([
    "docker-compose",
    "-f",
    dcPath,
    subcommand,
    ...parseKwargs(kwargs),
    // service names MUST go after the options
    ...(serviceNames || []),
    // Adding <&- to prevent interactive mode
    "<&-"
  ]);
}
```
Its a docker-compose up with more options, so it's no so different to how you run a container in the previous test.

**Comment by dapplion** [comment]
What your current guess on why limits are not applied?

**Comment by tropicar** [comment]
> Thanks for the detailed progress heart What is your current guess on why limits are not applied?
The problem seems to be related to how the dappmanager is starting the container/docker-compose. The reasons are below.

@3alpha suggested the next tests in order to know if the problem is because of how the dappmanager starts the container or the docker-compose itself.
1. Up the container directly inside of the dappmanager container. with the next command:
```
docker-compose -f /usr/src/app/dnp_repo/test-limit.public.dappnode.eth/docker-compose.yml up -d --force-recreate
```
The limits are not set up in the dappmanager container. 

2. Start the container using the same compose that is in the dappmanager container(this docker-compose has been parsed by the dappmanager).
Starting the docker-compose with the same options as the previous test, the limits are set up in the host and the package is installed.

The next steps i think it should be check what are all the options that are executed when a container is started and check the process of starting a container.

**Comment by tropicar** [comment]
The problem why the limitation is not set up definitely is because of the docker-compose version that is installed on the dappmanager's container. Currently, the dappamanager is using version 1.25.5 (you can see how this version is installed on this https://github.com/dappnode/DNP_DAPPMANAGER/blob/master/Dockerfile#L68 , there is an issue created to update how this installation process should be done https://github.com/dappnode/DNP_DAPPMANAGER/issues/1015 ). In this issue, you can find some context why docker-compose was installed in that way and why we will update that process.

Following with the explanation of why the docker-compose version is the cause of the error. You can replicate the error if you have a dappnode installed.

Access to your dappnode via ssh and go inside of the dappmanager container:
`docker exec -it DAppNodeCore-dappmanager.dnp.dappnode.eth /bin/sh`

Create a docker-compose file with the next content:
```
version: "3.5"
services:
 test:
    build:
      context: .
    image: "package"
    restart: always
    deploy:
      resources:
        limits:
          memory: 5000M
```
Create a Dockerfile with the next content:
```
FROM busybox

WORKDIR /usr/src/app

CMD ["top"]
```

## Current version of Docker-compose
Build the image with:
`docker-compose build`
And run the container:
`docker-compose up -d` 
Once the container is running, check with docker stats if the limitations of ram memory are set up:
`docker stats`
You will see the limits are not set up.

## Using the latest version of docker-compose
In this test, we will download a docker-compose binary and use it to build and run the container with limitations.
Download the lastest version(with version that are new but not the latest works too):
`curl -L https://github.com/docker/compose/releases//download/v2.5.0/docker-compose-Linux-$(uname -m) > /usr/src/app/docker-compose`
Give execution permissions to the binary:
`chmod +x docker-compose`
Build the docker-compose and execute using this binary:
`./docker-compose build`
`./docker-compose up -d`

In the same ways as before, check the limitations are set up with the command:
`docker stats`
And you will see the limitations are configured.
