### ISSUE TITLE
Domain scoped global envs - SPECS

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNode#69]
Add global ENVs to DAppNode. There will be two types of global envs.

## Domain-scoped global ENVs
Generated by specific DNPs. The DNPs will have to request access to each domain of ENVs in the manifest. They can also provide default values to the ENVs. The ENV values will be editable from the ADMIN UI just as regular ENVs. A file will be created in `DNCORE/dnp-name.global.dappnode.env`. 

The following simplified manifests exemplify a use case. The `bitcoin` DNP needs to set RPC credentials which the `ln` DNP needs to know in order to connect. The bitcoin DNP manifest declares a global ENVs domain `bitcoin.dnp.dappnode.eth` and declares their default values. Then, the `ln` DNP manifest declares again the same domain, but without providing values. 

```js
{
  name: "bitcoin.dnp.dappnode.eth",
  image: {
    globalEnvs: {
      bitcoin.dnp.dappnode.eth: {
        RPCUSER: "dappnode",
        RPCPASS: "dappnode",
      }
    }
  }
}
```

```js
{
  name: "ln.dnp.dappnode.eth",
  image: {
    globalEnvs: {
      bitcoin.dnp.dappnode.eth: {}
    }
  }
}
```

This will result in both DNPs having the `bitcoin.dnp.dappnode.eth.global.dappnode.env` file linked in the `env_file` section of the `docker-compose.yml` and the default values set.

> dnp_repo/bitcoin.dnp.dappnode.eth/docker-compose.yml
```yaml
bitcoin.dnp.dappnode.eth:
  env_file:
    - /usr/src/dappnode/DNCORE/bitcoin.dnp.dappnode.eth.global.dappnode.env
```

> dnp_repo/ln.dnp.dappnode.eth/docker-compose.yml
```yaml
ln.dnp.dappnode.eth:
  env_file:
    - /usr/src/dappnode/DNCORE/bitcoin.dnp.dappnode.eth.global.dappnode.env
```

> DNCORE/bitcoin.dnp.dappnode.eth.global.dappnode.env
```
RPCUSER=dappnode
RPCPASS=dappnode
```

## General global ENVs (archive)
Generated by default and accessible to all DNPs. They will be in the file in the `DNCORE/global.dappnode.env` file. Write access will be granted to all core DNPs through a WAMP RPC event. The DAPPMANAGER will pick it and modify the `.env` file. For now they will include:
  - EXTERNAL_IP: 85.84.83.82
  - INTERNAL_IP: 192.168.1.0
  - HOSTNAME: AmazingDAppnode
  - DOMAIN: ab34126ab.dyndns.dappnode.eth
which are computed by the VPN on startup. 

Motivation (by @eduadiez)
> To avoid that the packages have to consult centralized services to obtain the public IP address, we've to find a way to facilitate this ip from the DAPPMANAGER

These global ENVs will take effect to subsequently installed DNPs or any DNP restarted afterwards. In a normal case, these ENVs could be consumed by any non-core DNP as it will be started after the VPN has set them. 

Also the DAPPMANAGER will have to add the env_file by default to all DNPs

```yaml
mydnp.dnp.dappnode.eth:
  env_file:
    - /usr/src/dappnode/DNCORE/global.dappnode.env
```

## Challenges:
- How to control read / write access
  - Maybe domain scope ENVs are on a by-DNP basis, where only the user can change that ENVs on that specific DNP packages tab. Then other DNPs can consume them only.
- Show an alert to the user during installation that a DNP is requesting access to some global ENVs. Maybe show it on the `special permissions` box.

Linked to https://github.com/dappnode/DNP_DAPPMANAGER/issues/146
